### ISSUE TITLE
Unicode is deprecated and will be removed in atom 0.6.0

### ISSUE THREAD

**Issue by youpsla** [nucleic/atom#101]
Hello,
I have see this message while using 0.5.0. What to use instead of Unicode atm for not de deprecated in next version ? Haven't found informations so far.

Thanks

**Comment by MatthieuDartiailh** [comment]
Python 2 had `str` and `unicode` while Python 3 deals with `byte`s and `str` (ie unicode str). As a consequence Atom had `Bytes`, `Str` and `Unicode` to avoid version dependent behavior. Since we dropped support for Python 2, it makes sense to align Atom names with Python names and keep only `Bytes` and `Str`, so you should replace `Unicode` by `Str`.

Sorry my bad for the not so useful warning. I was planning a micro release for a corner case issue and I will update the warning message.

**Comment by youpsla** [comment]
Thanks a lots for your detailed answer.
