### ISSUE TITLE
Infer members from typehints

### ISSUE THREAD

**Issue by clamdad** [nucleic/atom#129]
Consider inferring members and behavior from python type hint syntax instead of atom.api types.

**Comment by MatthieuDartiailh** [comment]
I started working on this feature and I would like you opinion on some points @clamdad (in particular since I never used pydantic):

- currently I plan to allow type checking at runtime containers if the type is tuple, list, set or dict and a keyword argument was passed to the class at creation. One will be able to provide a depth at which to stop type checking.
- do not allow default values for things requiring to use Typed or Instance. We cannot use the usual atom strategy since we get an actual value, ways around it would involve to use deepcopy, we could make that behavior opt-in
- Forward(Typed/Instance/Subclass) are not supported
- Constant, ReadOnly, Enum, Coerced, Delegate, Event, Signal are not reachable from annotations

Does that sound reasonable ? I will try to have a PoC for you to play with by the end of next week.

**Comment by clamdad** [comment]
Looking great!  A lot of things I'd like to try.

Here is an adapted the Person class using
age as an `int`, with a custom validator

```python
class Person(Atom):
    last_name: str
    first_name: str
    age: int
    debug: bool = False

    def _validate_age(self, old, new):
        if age < 0:
            raise ValueError()
        return new    
```

Or we could use the Range member as-is:

```python
class Person(Atom):
    last_name: str
    first_name: str
    age = Range(low=0)
    debug: bool = False
```

Which kind of makes me wonder if we could infer constrained members with normal typing syntax:

```python
class Person(Atom):
    last_name: str
    first_name: str = 'Smith'
    age: Range(low=0) = 21
    debug: bool = False
```

**Comment by MatthieuDartiailh** [comment]
The issue with your last example is that without a plugin it will break mypy type checking which is a shame in my opinion.

**Comment by clamdad** [comment]
> The issue with your last example is that without a plugin it will break mypy type checking which is a shame in my opinion.

Looks like that's what [pydantic does]( https://pydantic-docs.helpmanual.io/mypy_plugin/).

**Comment by MatthieuDartiailh** [comment]
Looking at what the pydantic plugin does a similar plugin would not help for this particular case since it mainly focuses on providing information about behavior related by pydantic at runtime such as the generation of an `__init__` method.
