### ISSUE TITLE
Delegator, Signal, Event = ?

### ISSUE THREAD

**Issue by krey** [nucleic/atom#87]
What is `Delegator`?

What is `Signal`?

What is `Event`?

**Comment by MatthieuDartiailh** [comment]
You can look at the docstring of the member in the source which is pretty detailed or build the upcoming docs from https://github.com/nucleic/atom/pull/86 (You will need sphinx and run ``make html`` from the docs directory). The PR should be merged soon but the docs will not appear online for sometimes because of a name conflict on readthedocs.
